package courses

import (
	"net/http"
	"time"
	db "tourbackend/database/gen"
	"tourbackend/handlers"
	"tourbackend/utils"

	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
)

type CourseHandler struct {
	*handlers.Handler
}

func NewCourseHandler(queries *db.Queries) *CourseHandler {
	return &CourseHandler{
		handlers.NewHandler(queries),
	}
}

type CreateCourseRequest struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateCourseResponse struct {
	Uuid        string `json:"uuid"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

func (h *CourseHandler) CreateCourse(c echo.Context) error {
	r := h.NewReqCtx(c)

	var req CreateCourseRequest
	if err := c.Bind(&req); err != nil {
		return r.Error(http.StatusBadRequest, "invalid request")
	}

	unixTime := time.Now().Unix()

	course, err := r.Queries.CreateCourse(r.Ctx, db.CreateCourseParams{
		Uuid:        uuid.NewString(),
		Name:        req.Name,
		Description: req.Description,
		CreatedAt:   unixTime,
		UpdatedAt:   unixTime,
	})
	if err != nil {
		return err
	}

	return c.JSON(http.StatusCreated, CreateCourseResponse{
		Uuid:        course.Uuid,
		Name:        course.Name,
		Description: course.Description,
		CreatedAt:   utils.UnixToIso(course.CreatedAt),
		UpdatedAt:   utils.UnixToIso(course.UpdatedAt),
	})
}

// this struct doesn't have to exist now as the autogenerated db
// struct is the same, but in future this struct will have to be
// extended with additional info like course materials and quizes
type GetCourseResponse struct {
	Uuid        string `json:"uuid"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (h *CourseHandler) GetCourse(c echo.Context) error {
	r := h.NewReqCtx(c)

	uuid := c.Param("uuid")

	if uuid == "" {
		return r.Error(http.StatusBadRequest, "Must specify the course uuid.")
	}

	course, err := r.Queries.GetCourse(r.Ctx, uuid)
	if err != nil {
		if utils.IsNoRowsError(err) {
			return r.Error(http.StatusNotFound, "The requested resource was not found.")
		}

		return r.Error(http.StatusInternalServerError, "Failed to fetch the course from the database.")
	}

	courseDetail := GetCourseResponse{
		Uuid:        course.Uuid,
		Name:        course.Name,
		Description: course.Description,
	}

	return c.JSON(http.StatusOK, courseDetail)

}

type UpdateCourseRequest struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type UpdateCourseResponse struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

func (h *CourseHandler) UpdateCourse(c echo.Context) error {
	r := h.NewReqCtx(c)

	uuid := c.Param("uuid")
	if uuid == "" {
		return r.Error(http.StatusBadRequest, "invalid request")
	}

	var req UpdateCourseRequest
	if err := c.Bind(&req); err != nil {
		return r.Error(http.StatusBadRequest, "invalid request")
	}

	unixTime := time.Now().Unix()

	course, err := r.Queries.UpdateCourse(r.Ctx, db.UpdateCourseParams{
		Name:        req.Name,
		Description: req.Description,
		UpdatedAt:   unixTime,
		Uuid:        uuid,
	})
	if err != nil {
		if utils.IsNoRowsError(err) {
			return r.Error(http.StatusNotFound, "The requested resource was not found.")
		}
		return r.Error(http.StatusInternalServerError, "Failed to delete the course.")
	}

	return c.JSON(http.StatusCreated, UpdateCourseResponse{
		Name:        course.Name,
		Description: course.Description,
		CreatedAt:   utils.UnixToIso(course.CreatedAt),
		UpdatedAt:   utils.UnixToIso(course.UpdatedAt),
	})
}

func (h *CourseHandler) DeleteCourse(c echo.Context) error {
	r := h.NewReqCtx(c)

	uuid := c.Param("uuid")

	if uuid == "" {
		return r.Error(http.StatusBadRequest, "Uuid must be provided as path parameter")
	}

	res, err := r.Queries.DeleteCourse(r.Ctx, uuid)
	if err != nil {
		return r.Error(http.StatusInternalServerError, "Failed to delete the course.")
	}

	n, err := res.RowsAffected()
	if err != nil {
		return r.Error(http.StatusInternalServerError, "Failed to delete the course.")
	}

	if n == 0 {
		return r.Error(http.StatusNotFound, "The requested resource was not found.")
	}

	return r.JSONMsg(http.StatusNoContent, "Deleted the course.")
}

type ListAllCoursesResponse struct {
	Uuid        string `json:"uuid"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

func (h *CourseHandler) ListAllCourses(c echo.Context) error {
	r := h.NewReqCtx(c)

	courses, err := r.Queries.ListAllCourses(r.Ctx)
	if err != nil {
		return r.Error(http.StatusInternalServerError, "Failed to fetch courses from the database.")
	}

	formattedCourses := make([]ListAllCoursesResponse, len(courses))
	for i, course := range courses {
		formattedCourses[i] = ListAllCoursesResponse{
			Uuid:        course.Uuid,
			Name:        course.Name,
			Description: course.Description,
			CreatedAt:   utils.UnixToIso(course.CreatedAt),
			UpdatedAt:   utils.UnixToIso(course.UpdatedAt),
		}
	}

	return c.JSON(http.StatusOK, formattedCourses)
}
